# Use an official Python runtime as a parent image
FROM python:3.6.3
ENV PYTHONUNBUFFERED 1
RUN mkdir /flight_booking
# Set the working directory to /flight_booking
WORKDIR /flight_booking

# Copy the current directory contents into the container at /flight_booking
COPY . /flight_booking/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
